databases:
  - name: embarque2db
    plan: free
    databaseName: embarque2db
    user: embarque2

services:
  - type: web
    plan: free
    name: embarque2
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: embarque2db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
